name: Deploy-EC2

on:
  workflow_call:

jobs:

  deploy_ec2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.0.0
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.0.0
      with:
        name: go-api

    - name: Deploy to Dev server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export DBHOST=${{ secrets.DB_HOST }}
          export DBUSER=${{ secrets.DB_USER }}
          export DBPASSWORD=${{ secrets.DB_PASSWORD }}
          export DBNAME=${{ secrets.DB_NAME }}
          export DBPORT=${{ secrets.DB_PORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &

